import Head from 'next/head';
import BaseLayout from '@/components/BaseLayout';
import { Inter } from '@next/font/google';

// NOTE: 字体的使用
const inter = Inter({ subsets: ['latin'] });
/*
  在要使用字体的地方- className加上 inter.className
  <p className={inter.className}>...</p>
 */

export default function Home() {
  return (
    <>
      <Head>
        <title>events</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <BaseLayout>
        <section className="flex flex-col justify-center items-center space-y-10 mt-4">
          <div>
            <h1 className={inter.className}>events</h1>
          </div>
        </section>
      </BaseLayout>
    </>
  );
}
