import Head from 'next/head'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'

// NOTE: 字体的使用
const inter = Inter({ subsets: ['latin'] })
/*
  在要使用字体的地方- className加上 inter.className
  <p className={inter.className}>...</p>
 */

export default function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <p className={inter.className}>Start Project</p>
    </>
  )
}
